export const YOUTUBE_VIDEO_REQUEST = "YOUTUBE_VIDEO_REQUEST";
export const YOUTUBE_VIDEO_SUCCESS = "YOUTUBE_VIDEO_SUCCESS";
export const YOUTUBE_VIDEO_FAIL = "YOUTUBE_VIDEO_FAIL";

export const YOUTUBE_VIDEO_DETAILS_REQUEST = "YOUTUBE_VIDEO_DETAILS_REQUEST";
export const YOUTUBE_VIDEO_DETAILS_SUCCESS = "YOUTUBE_VIDEO_DETAILS_SUCCESS";
export const YOUTUBE_VIDEO_DETAILS_FAIL = "YOUTUBE_VIDEO_DETAILS_FAIL";
